# Generated by Django 2.2.24 on 2022-05-02 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentID', models.IntegerField()),
                ('studentName', models.CharField(max_length=100)),
                ('studentPass', models.CharField(max_length=100)),
                ('studentAddr', models.CharField(max_length=100)),
                ('studentMobono', models.IntegerField()),
            ],
        ),
    ]
