# Generated by Django 2.2.24 on 2022-06-07 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('contact', models.IntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('passwd', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=100)),
            ],
        ),
    ]
