# Generated by Django 2.2.24 on 2022-06-12 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form1', '0002_auto_20220610_1747'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentRegistration',
            new_name='StudentModel',
        ),
    ]
