# Generated by Django 2.2.24 on 2022-06-12 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form1', '0003_auto_20220612_0431'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('teacher_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='StudentModel',
        ),
    ]
