# Generated by Django 2.2.24 on 2022-06-07 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='comment',
            field=models.CharField(default='not available', max_length=100),
        ),
    ]
