# Generated by Django 2.2.24 on 2022-06-07 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Enroll', '0002_student_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='passwd',
        ),
    ]
