# Generated by Django 2.2.24 on 2022-04-30 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuid', models.IntegerField()),
                ('stuname', models.CharField(max_length=100)),
                ('stuaddr', models.CharField(max_length=100)),
                ('stupass', models.CharField(max_length=100)),
                ('stucomment', models.CharField(max_length=100)),
                ('stumobno', models.IntegerField(max_length=100)),
            ],
        ),
    ]
